/// Flutter icons IconPack
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  IconPack
///      fonts:
///       - asset: fonts/IconPack.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class IconPack {
  IconPack._();

  static const _kFontFam = 'IconPack';
  static const String? _kFontPkg = null;

  static const IconData adult = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plane_outline = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basket = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ammo_bag = IconData(0xe905, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bone_knife = IconData(0xe939, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bowie_knife = IconData(0xe940, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossbow = IconData(0xe978, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crystal_wand = IconData(0xe984, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frostfire = IconData(0xe9d7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health = IconData(0xe9f5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData monster_skull = IconData(0xea43, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rune_stone = IconData(0xea89, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy = IconData(0xead7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coin = IconData(0xeaec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData movie = IconData(0xf040, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield = IconData(0xf38e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volleyball_ball = IconData(0xf45f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skull = IconData(0xf54c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fist_raised = IconData(0xf6de, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
