

import 'package:SoloLife/app/data/models/shopItem.dart';


  List<String> itemsPlane = [
    "AgilityRune","IntelligenceRune","ManaRune",
    "StrengthRune","VitalityRun","SenseRune"]; 

Map<String, dynamic> archive = {
  "MoonFrame":ShopItem(title:"Moon Frame",image:"assets/images/frames/moon.png", price: 500,itemType: "frame",id:"MoonFrame"),
  "CloudFrame":ShopItem(title:"Cloud Frame",image:"assets/images/frames/cloud.png", price: 0,itemType: "frame", id: "CloudFrame"),
  "TaiShiFrame":ShopItem(title:"art Frame",image:"assets/images/frames/shi.png", price: 500,itemType: "frame", id: "TaiShiFrame"),
  "StrengthRune":ShopItem(title:"Strength Rune",image:"assets/images/icon.png", price: 1500,itemType: "Rune", id: "StrengthRune"),
  "VitalityRun":ShopItem(title:"Vitality Rune",image:"assets/images/icon.png", price: 1500,itemType: "Rune", id: "VitalityRun"),
  "Kitsunee" :ShopItem(title:"Kitsunee Frame",image:"assets/images/frames/limited.png", price: 0,itemType: "frame",id:"Kitsunee"),
  "SenseRune":ShopItem(title:"Sense Rune",image:"assets/images/icon.png", price: 1500,itemType: "Rune", id: "SenseRune"),
   "FoxFrame":ShopItem(title:"Fox Frame",image:"assets/images/frames/fox.png", price: 500,itemType: "frame",id:"FoxFrame"),
  "GoldFrame1":ShopItem(title:"Gold1 Frame",image:"assets/images/frames/gold1.png", price: 0,itemType: "frame",id:"GoldFrame1"),
  "GoldFrame2":ShopItem(title:"Gold2 Frame",image:"assets/images/frames/gold2.png", price: 500,itemType: "frame",id:"GoldFrame2"),
  "DemonFrame":  ShopItem(title:"Demon Frame",image:"assets/images/frames/demon.png", price: 500,itemType: "frame",id:"DemonFrame"),
  "Myst'sBox" :ShopItem(title:"Myst'sBox",image:"assets/images/icon.png", price: 15000,itemType: "Box",id:"Myst'sBox"),
  "Myst'sBoxCurse": ShopItem(title:"Myst'sBox Curse",image:"assets/images/icon.png", price: 1000,itemType: "Box",id:"Myst'sBoxCurse"),
  "Myst'sBoxOld":ShopItem(title:"Myst'sBox Old",image:"assets/images/icon.png", price: 5000,itemType: "Box",id:"Myst'sBoxOld"),
  "CoinsBag":ShopItem(title: "coins bag", image: "assets/images/icon.png", price: 0, itemType: "coins", id: "CoinsBag"),
  "AnimatedFrame":  ShopItem(title:"animated Frame",image:"assets/images/frames/animated.png", price: 500,itemType: "frame",id:"AnimatedFrame"),
  "ChildFrame":  ShopItem(title:"child Frame",image:"assets/images/frames/child.png", price: 500,itemType: "frame",id:"ChildFrame"),
  "GrassFrame":  ShopItem(title:"grass Frame",image:"assets/images/frames/grass.png", price: 500,itemType: "frame",id:"GrassFrame"),
  "HomeFrame":  ShopItem(title:"home Frame",image:"assets/images/frames/homi.png", price: 500,itemType: "frame",id:"HomeFrame"),
  "HpYpFrame":  ShopItem(title:"Hoyo Frame",image:"assets/images/frames/hpyp.png", price: 500,itemType: "frame",id:"HpYpFrame"),
  "IDontFrame":  ShopItem(title:"Something Frame",image:"assets/images/frames/idontknow.png", price: 500,itemType: "frame",id:"IDontFrame"),
  "McFrame":  ShopItem(title:"Mc Frame",image:"assets/images/frames/mc.png", price: 500,itemType: "frame",id:"McFrame"),
  "newYearFrame":  ShopItem(title:"NewYear Frame",image:"assets/images/frames/newyear.png", price: 500,itemType: "frame",id:"newYearFrame"),
  "NovFrame":  ShopItem(title:"Novilat Frame",image:"assets/images/frames/novilat.png", price: 500,itemType: "frame",id:"NovFrame"),
  "RamadanFrame":  ShopItem(title:"Ramadan Frame",image:"assets/images/frames/ramadan.png", price: 500,itemType: "frame",id:"RamadanFrame"),
  "SilverFrame":  ShopItem(title:"Silver Frame",image:"assets/images/frames/silver.png", price: 500,itemType: "frame",id:"SilverFrame"),
  "TravlerFrame":  ShopItem(title:"Travler Frame",image:"assets/images/frames/travler.png", price: 500,itemType: "frame",id:"TravlerFrame"),
  "WeedFrame":  ShopItem(title:"Weed Frame",image:"assets/images/frames/weed.png", price: 500,itemType: "frame",id:"WeedFrame"),
  "xiaoFrame":  ShopItem(title:"Xiao Frame",image:"assets/images/frames/xiao.png", price: 500,itemType: "frame",id:"xiaoFrame"),
  "yayFrame":  ShopItem(title:"Yay Frame",image:"assets/images/frames/yay.png", price: 500,itemType: "frame",id:"yayFrame"),
  };

Map<String, double> itemProbabilities = {
  'MoonFrame': 0.01,
  'CloudFrame': 0.02,
  'TaiShiFrame': 0.01,
  'StrengthRune': 0.000001,
  'VitalityRun': 0.000001,
  'Kitsunee': 0.09,
  'SenseRune': 0.000001,
  'FoxFrame': 0.05,
  'GoldFrame1': 0.05,
  'GoldFrame2': 0.05,
  'DemonFrame': 0.01,
  "CoinsBag": 0.8, // Adjusted probability
  "AnimatedFrame":0.01,
  "ChildFrame":0.2,
  "GrassFrame":0.2,
  "HomeFrame":0.2,
  "HpYpFrame":0.3,
  "IDontFrame":0.1,
  "McFrame":0.1,
  "newYearFrame":0.3,
  "NovFrame":0.4,
  "RamadanFrame":0.2,
  "SilverFrame":0.2,
  "TravlerFrame":0.2,
  "WeedFrame":0.3,
  "xiaoFrame":0.3,
  "yayFrame":0.2,
};

Map<String, double> oldItemProbabilities = {
  'MoonFrame': 0.009,
  'CloudFrame': 0.009,
  'TaiShiFrame': 0.009,
  'StrengthRune': 0.0000009,
  'VitalityRun': 0.0000009,
  'Kitsunee': 0.09,
  'SenseRune': 0.0000009,
  'FoxFrame': 0.007,
  'GoldFrame1': 0.007,
  'GoldFrame2': 0.007,
  'DemonFrame': 0.009,
  "CoinsBag": 0.8, // Adjusted probability
    "AnimatedFrame":0.01,
  "ChildFrame":0.09,
  "GrassFrame":0.09,
  "HomeFrame":0.09,
  "HpYpFrame":0.1,
  "IDontFrame":0.07,
  "McFrame":0.07,
  "newYearFrame":0.1,
  "NovFrame":0.2,
  "RamadanFrame":0.1,
  "SilverFrame":0.1,
  "TravlerFrame":0.1,
  "WeedFrame":0.09,
  "xiaoFrame":0.1,
  "yayFrame":0.07,
};

Map<String, double> curseItemProbabilities = {
  'MoonFrame': 0.003,
  'CloudFrame': 0.003,
  'TaiShiFrame': 0.004,
  'StrengthRune': 0.0000001,
  'VitalityRun': 0.0000001,
  'Kitsunee': 0.009,
  'SenseRune': 0.0000001,
  'FoxFrame': 0.005,
  'GoldFrame1': 0.005,
  'GoldFrame2': 0.005,
  'DemonFrame': 0.003,
  "CoinsBag": 0.009, // Adjusted probability
    "AnimatedFrame":0.0001,
  "ChildFrame":0.002,
  "GrassFrame":0.002,
  "HomeFrame":0.002,
  "HpYpFrame":0.003,
  "IDontFrame":0.001,
  "McFrame":0.001,
  "newYearFrame":0.003,
  "NovFrame":0.004,
  "RamadanFrame":0.002,
  "SilverFrame":0.002,
  "TravlerFrame":0.002,
  "WeedFrame":0.003,
  "xiaoFrame":0.003,
  "yayFrame":0.002,
};